clear
echo ""
echo "  ╔═══════════════════════════════════════════════════════════════════════════════════╗"
echo "  ║       Mellea Skills Compiler CLI - Agent specification certification pipeline     ║"
echo "  ╚═══════════════════════════════════════════════════════════════════════════════════╝"
echo ""
echo "  Installed tools:"
echo "    • mellea-skills   $(mellea-skills version 2>/dev/null || echo '(not found)')"
echo "    • claude          $(claude --version 2>/dev/null | head -1 || echo '(not found)')"
echo "    • bob             $(bob --version 2>/dev/null | head -1 || echo '(not found)') (IBM Bob)"
echo "    • python          $(python --version 2>/dev/null || echo '(not found)')"
echo ""
echo "  Usage: mellea-skills [OPTIONS] COMMAND [ARGS]..."
echo ""
echo "  Commands:"
echo "    compile   Melleafy Compile: Decompose an Agent Spec into Mellea Code"
echo "    validate  Validate a compiled Mellea skill (Step 7 lints + fixture smoke-check)"
echo "    run       Run Mellea Skill Pipeline"
echo "    ingest    Run Risk Analysis and Policy Generation Pipeline for Mellea skills"
echo "    certify   Run Full Certification Pipeline for Mellea skill"
echo "    export    [EXPERIMENTAL] Export a compiled Mellea skill to a deployment target"
echo "    version   Mellea Skills Compiler Version"
echo ""
echo "  Quick start:"
echo "    mellea-skills compile /skills/weather"
echo "    mellea-skills run /skills/weather/weather_mellea --input 'What is the weather like in Dublin?'"
echo "    mellea-skills certify /skills/weather/weather_mellea"
echo "    mellea-skills export /skills/weather/weather_mellea --target mcp"
echo ""
echo "  For Help:"
echo "    mellea-skills --help"
echo ""
